Repository kubernetes-sigs/etcd-manager, pull requests merged in 2024-10, with the labels that each got.

#11 Release 2024.10.11
  .github/workflows/tag-release.yml
  dev/tag-release.sh
Labels: lgtm, cncf-cla: yes, approved, tide/merge-method-squash, size/XS

#12 Fix release 2024.10.11
  .github/workflows/tag-release.yml
  version.txt
Labels: lgtm, cncf-cla: yes, approved, size/XS

#10 make logs related to refreshControlStore more informative
  pkg/controller/commands.go
  pkg/controller/controller.go
  pkg/controller/upgrade.go
Labels: lgtm, cncf-cla: yes, approved, size/XS

#13 chore: fix version extraction from tags
  dev/push-etcd-manager.sh
  docs/release-process.md
Labels: size/S, lgtm, cncf-cla: yes, approved

#14 Release v3.0.20241012
  version.txt
Labels: lgtm, cncf-cla: yes, approved, size/XS

#15 doc: Fix release proces `kpromo cip` snapshot URL
  docs/release-process.md
Labels: lgtm, cncf-cla: yes, approved, size/XS
